# Convenio de consignación vigente — MYM BOBINADOS, bodega 59

Diagnóstico del funcionamiento, uso, nivel pactado y retorno del convenio. El análisis
trabaja en modo lectura y cruza ventas, snapshots mensuales y el acuerdo exacto SKF.

La identidad principal es el `idproducto` exacto porque el acuerdo distingue variantes
con y sin grasa GJN. La llave canónica solo se utiliza como apoyo para detectar compras
equivalentes de otra marca.

## Parámetros y acuerdo pactado

Las reglas de decisión son visibles y ajustables. La cobertura objetivo conserva la
regla simple usada para SERMOTOR.

In [1]:
from io import StringIO
from pathlib import Path
import math
import sqlite3
import numpy as np
import pandas as pd
from IPython.display import display

from scripts.analyze_sermotor_consignacion import normalize_designation, ceil_even

IDBODEGA = 59
DB_PATH = Path("database/commercial.db")
MESES_COBERTURA_OBJETIVO = 2.5
COBERTURA_BAJA_MESES = 2.0
COBERTURA_ALTA_MESES = 8.0

ACUERDO_CSV = """codigo,marca,unidades_pactadas
400160SKF,SKF,3
400200SKF,SKF,10
400250SKF,SKF,9
400300SKF,SKF,6
400350SKF,SKF,8
400400SKF,SKF,4
400450SKF,SKF,4
400500SKF,SKF,2
400550SKF,SKF,2
400600SKF,SKF,1
400650SKF,SKF,5
400700SKF,SKF,4
400750SKF,SKF,5
400800SKF,SKF,3
400850SKF,SKF,5
400900SKF,SKF,4
401000SKF,SKF,1
6004-2Z/C3GJNSKF,SKF,10
6005-2RSH/C3GJNSKF,SKF,10
6005-2Z/C3GJNSKF,SKF,10
6006-2Z/C3GJNSKF,SKF,1
6007-2RS1/C3GJNSKF,SKF,9
6008-2Z/C3GJNSKF,SKF,2
6200-2Z/C3GJNSKF,SKF,4
6201-2RSH/C3GJNSKF,SKF,5
6201-2Z/C3GJNSKF,SKF,6
6202-2RSH/C3GJNSKF,SKF,18
6202-2Z/C3GJNSKF,SKF,7
6203-2RSH/C3GJNSKF,SKF,4
6203-2Z/C3GJNSKF,SKF,6
6204-2RSH/C3GJNSKF,SKF,7
6204-2Z/C3GJNSKF,SKF,10
6205-2RSH/C3GJNSKF,SKF,5
6205-2Z/C3GJNSKF,SKF,8
6206-2Z/C3GJNSKF,SKF,5
6207-2RS1/C3GJNSKF,SKF,9
6207-2Z/C3GJNSKF,SKF,5
6208-2RS1/C3GJNSKF,SKF,6
6208-2Z/C3GJNSKF,SKF,5
6209-2RS1/C3GJNSKF,SKF,3
6209-2Z/C3GJNSKF,SKF,6
6210-2RS1/C3GJNSKF,SKF,6
6210-2Z/C3GJNSKF,SKF,9
6211-2RS1/C3GJNSKF,SKF,5
6211-2RS1/C3SKF,SKF,1
6211-2Z/C3SKF,SKF,4
6212-2RS1/C3GJNSKF,SKF,5
6212-2Z/C3GJNSKF,SKF,4
6213-2RS1/C3GJNSKF,SKF,4
6213-2RS1/C3SKF,SKF,2
6213-2Z/C3GJNSKF,SKF,8
6213-2Z/C3SKF,SKF,1
6214-2RS1/C3SKF,SKF,4
6214-2Z/C3SKF,SKF,3
6215-2RS1/C3SKF,SKF,5
6215-2Z/C3GJNSKF,SKF,2
6216-2Z/C3SKF,SKF,2
6217-2Z/C3SKF,SKF,2
6218-2Z/C3SKF,SKF,1
6300-2RSH/C3GJNSKF,SKF,5
6300-2Z/C3SKF,SKF,4
6302-2RSH/C3GJNSKF,SKF,4
6302-2Z/C3GJNSKF,SKF,6
6303-2RSH/C3GJNSKF,SKF,2
6303-2Z/C3GJNSKF,SKF,2
6304-2RSH/C3GJNSKF,SKF,4
6304-2Z/C3GJNSKF,SKF,4
6305-2RS1/C3GJNSKF,SKF,3
6305-2Z/C3GJNSKF,SKF,2
6306-2RS1/C3GJNSKF,SKF,4
6306-2Z/C3GJNSKF,SKF,6
6307-2RS1/C3GJNSKF,SKF,8
6307-2Z/C3GJNSKF,SKF,4
6308-2RS1/C3GJNSKF,SKF,7
6308-2Z/C3GJNSKF,SKF,8
6309-2RS1/C3GJNSKF,SKF,11
6309-2Z/C3GJNSKF,SKF,5
6310-2RS1/C3GJNSKF,SKF,4
6310-2RS1/C3SKF,SKF,4
6310-2Z/C3GJNSKF,SKF,9
6311-2RS1/C3GJNSKF,SKF,3
6311-2Z/C3GJNSKF,SKF,5
6312-2RS1/C3GJNSKF,SKF,4
6312-2Z/C3GJNSKF,SKF,4
6313-2RS1/C3GJNSKF,SKF,5
6313-2Z/C3GJNSKF,SKF,2
6313-2Z/C3SKF,SKF,1
6314-2RS1/C3GJNSKF,SKF,4
6314-2Z/C3GJNSKF,SKF,2
6314-2Z/C3SKF,SKF,4
6315-2RS1/C3GJNSKF,SKF,3
6315-2Z/C3GJNSKF,SKF,3
6316-2RS1/C3SKF,SKF,3
6316-2Z/C3SKF,SKF,2
6316/C3SKF,SKF,2
6319/C3SKF,SKF,2
7312 BECBJSKF,SKF,2
99235SKF,SKF,2
NJ 220 ECJ/C3SKF,SKF,1
NU 2211 ECP/C3SKF,SKF,1"""
acuerdo = pd.read_csv(StringIO(ACUERDO_CSV), dtype={"codigo": str})
acuerdo["codigo"] = acuerdo["codigo"].str.strip()
assert not acuerdo["codigo"].duplicated().any()

pd.set_option("display.max_rows", 250)
pd.set_option("display.max_columns", 60)
PESO = "${:,.0f}".format

## Paso 0 — Identidad y calidad de datos

Se verifica el cliente dominante, los cruces exactos del acuerdo y las fechas efectivas
de snapshot. Un mes ausente no se interpola ni se inventa.

In [2]:
uri = f"file:{DB_PATH}?mode=ro"
with sqlite3.connect(uri, uri=True) as con:
    ventas = pd.read_sql_query(
        "SELECT * FROM raw_sales WHERE CAST(idbodega AS TEXT)=?",
        con, params=(str(IDBODEGA),),
    )
    inventario = pd.read_sql_query(
        "SELECT * FROM inventario_snapshot WHERE CAST(idbodega AS TEXT)=?",
        con, params=(str(IDBODEGA),),
    )

ventas["fecha"] = pd.to_datetime(ventas["fecha"], errors="raise")
inventario["fecha_snapshot"] = pd.to_datetime(
    inventario["fecha_snapshot"], errors="raise"
)
identidad = (
    ventas.groupby(["nit", "razonsocial"], dropna=False)
    .agg(lineas=("idproducto", "size"), fecha_min=("fecha", "min"),
         fecha_max=("fecha", "max"))
    .reset_index().sort_values("lineas", ascending=False)
)
display(identidad)

fechas_snapshot = sorted(inventario["fecha_snapshot"].dropna().unique())
calendario = pd.DataFrame({"fecha_snapshot": fechas_snapshot})
calendario["mes"] = calendario["fecha_snapshot"].dt.strftime("%Y-%m")
esperados = pd.date_range(
    calendario["fecha_snapshot"].min(),
    calendario["fecha_snapshot"].max(), freq="MS",
)
faltantes = sorted(set(esperados) - set(fechas_snapshot))
display(calendario)
print("Meses faltantes:", ", ".join(pd.Timestamp(x).strftime("%Y-%m") for x in faltantes) or "Ninguno")

sales_codes = set(ventas["idproducto"].dropna().astype(str))
inventory_codes = set(inventario["idproducto"].dropna().astype(str))
cruce = acuerdo.assign(
    existe_ventas=acuerdo["codigo"].isin(sales_codes),
    existe_inventario=acuerdo["codigo"].isin(inventory_codes),
)
no_cruzan = cruce[~cruce["existe_ventas"] | ~cruce["existe_inventario"]]
display(no_cruzan)
print(
    f"Acuerdo: {len(acuerdo)} referencias; "
    f"sin cruce completo: {len(no_cruzan)}."
)

         nit                        razonsocial  lineas  fecha_min  fecha_max
1  805015031     MYM BOBINADOS INDUSTRIALES SAS    1203 2023-01-18 2025-10-16
0  805015031  MYM BOBINADOS INDUSTRIALES S.A.S.     250 2025-10-27 2026-07-14

  fecha_snapshot      mes
0     2026-01-01  2026-01
1     2026-02-01  2026-02
2     2026-03-01  2026-03
3     2026-04-01  2026-04
4     2026-05-01  2026-05
5     2026-06-01  2026-06
6     2026-07-01  2026-07

Meses faltantes: Ninguno

,codigo,marca,unidades_pactadas,existe_ventas,existe_inventario
20,6006-2Z/C3GJNSKF,SKF,1,True,False
44,6211-2RS1/C3SKF,SKF,1,True,False
45,6211-2Z/C3SKF,SKF,4,True,False
48,6213-2RS1/C3GJNSKF,SKF,4,True,False
51,6213-2Z/C3SKF,SKF,1,True,False
52,6214-2RS1/C3SKF,SKF,4,False,False
53,6214-2Z/C3SKF,SKF,3,True,False
54,6215-2RS1/C3SKF,SKF,5,True,False
56,6216-2Z/C3SKF,SKF,2,False,False
58,6218-2Z/C3SKF,SKF,1,True,False
60,6300-2Z/C3SKF,SKF,4,True,False
63,6303-2RSH/C3GJNSKF,SKF,2,True,False
64,6303-2Z/C3GJNSKF,SKF,2,True,False
78,6310-2RS1/C3SKF,SKF,4,True,False
86,6313-2Z/C3SKF,SKF,1,True,False
89,6314-2Z/C3SKF,SKF,4,True,False
92,6316-2RS1/C3SKF,SKF,3,True,False
93,6316-2Z/C3SKF,SKF,2,True,False
94,6316/C3SKF,SKF,2,True,False
95,6319/C3SKF,SKF,2,True,False
96,7312 BECBJSKF,SKF,2,False,False
97,99235SKF,SKF,2,True,False
98,NJ 220 ECJ/C3SKF,SKF,1,False,False
99,NU 2211 ECP/C3SKF,SKF,1,False,False

Acuerdo: 100 referencias; sin cruce completo: 24.

## Bloque A — ¿El proceso funciona?

Sin movimientos de traslado no existe una medición independiente del consumo implícito:
la reposición es una incógnita. Para no fingir precisión, se muestran tres cantidades:

- **Consumo sin reposición:** stock inicial menos stock final.
- **Facturado:** ventas netas de la bodega durante el intervalo.
- **Reposición implícita:** facturado + stock final − stock inicial; es la reposición
  necesaria para reconciliar ambos datos.

Una reposición implícita negativa se marca como brecha porque apunta a transferencias,
ajustes, mermas, devoluciones o diferencias de corte.

Con reposición semanal, un inventario plano o cercano al pactado **no es evidencia de
sobrestock**. Las columnas de ceros e inventario medio frente al pacto se conservan
únicamente para diagnosticar si el proceso de reposición parece cumplirse. Los snapshots
mensuales no permiten comprobar el comportamiento semana a semana.

In [3]:
start = calendario["fecha_snapshot"].min()
end = calendario["fecha_snapshot"].max()
ventas_periodo = ventas[ventas["fecha"].ge(start) & ventas["fecha"].lt(end)].copy()

stock = inventario.pivot_table(
    index="idproducto", columns="fecha_snapshot", values="unidades",
    aggfunc="sum", fill_value=0,
)
intervalos = []
for left, right in zip(fechas_snapshot[:-1], fechas_snapshot[1:]):
    sold = (
        ventas[ventas["fecha"].ge(left) & ventas["fecha"].lt(right)]
        .groupby("idproducto")["cantidad"].sum()
    )
    keys = stock.index.union(sold.index)
    s0 = stock[left].reindex(keys, fill_value=0)
    s1 = stock[right].reindex(keys, fill_value=0)
    billed = sold.reindex(keys, fill_value=0)
    part = pd.DataFrame({
        "periodo": f"{pd.Timestamp(left):%Y-%m-%d} → {pd.Timestamp(right):%Y-%m-%d}",
        "idproducto": keys,
        "stock_inicial": s0.values,
        "stock_final": s1.values,
        "consumo_sin_reposicion": (s0 - s1).values,
        "facturado": billed.values,
        "reposicion_implicita": (billed + s1 - s0).values,
    })
    part["brecha_sin_reposicion"] = (
        part["consumo_sin_reposicion"] - part["facturado"]
    )
    intervalos.append(part)
movimientos = pd.concat(intervalos, ignore_index=True)
resumen_intervalos = (
    movimientos.groupby("periodo")
    .agg(
        stock_inicial=("stock_inicial", "sum"),
        stock_final=("stock_final", "sum"),
        consumo_sin_reposicion=("consumo_sin_reposicion", "sum"),
        facturado=("facturado", "sum"),
        reposicion_implicita=("reposicion_implicita", "sum"),
        brecha_sin_reposicion=("brecha_sin_reposicion", "sum"),
        referencias_reposicion_negativa=(
            "reposicion_implicita", lambda x: int((x < 0).sum())
        ),
    ).reset_index()
)
display(resumen_intervalos)

acuerdo_stock = stock.reindex(acuerdo["codigo"]).fillna(0)
ventas_por_codigo = ventas_periodo.groupby("idproducto")["cantidad"].sum()
zero_counts = (acuerdo_stock == 0).sum(axis=1)
flat = pd.DataFrame({
    "codigo": acuerdo["codigo"],
    "stock_inicial": acuerdo["codigo"].map(acuerdo_stock.iloc[:, 0]),
    "stock_final": acuerdo["codigo"].map(acuerdo_stock.iloc[:, -1]),
    "desviacion_snapshots": acuerdo["codigo"].map(acuerdo_stock.std(axis=1)),
    "consumo_facturado": acuerdo["codigo"].map(ventas_por_codigo).fillna(0),
    "veces_en_cero": acuerdo["codigo"].map(zero_counts).fillna(
        len(fechas_snapshot)
    ).astype(int),
    "inventario_promedio": acuerdo["codigo"].map(
        acuerdo_stock.mean(axis=1)
    ).fillna(0),
})
flat = flat.merge(
    acuerdo[["codigo", "unidades_pactadas"]], on="codigo", how="left"
)
flat["inventario_medio_vs_pactado"] = np.where(
    flat["unidades_pactadas"] > 0,
    flat["inventario_promedio"] / flat["unidades_pactadas"], np.nan,
)
flat["senal"] = np.select(
    [
        flat["consumo_facturado"].gt(0)
        & flat["inventario_promedio"].eq(0),
        flat["consumo_facturado"].gt(0)
        & flat["desviacion_snapshots"].fillna(0).eq(0),
    ],
    [
        "VENTA_SIN_CRUCE_INVENTARIO",
        "STOCK_PLANO_COMPATIBLE_REPOSICION_SEMANAL",
    ],
    default="SIN_ALERTA",
)
display(flat[flat["senal"] != "SIN_ALERTA"])

,periodo,stock_inicial,stock_final,consumo_sin_reposicion,facturado,reposicion_implicita,brecha_sin_reposicion,referencias_reposicion_negativa
0,2026-01-01 → 2026-02-01,391.0,363.0,28.0,114.0,86.0,-86.0,0
1,2026-02-01 → 2026-03-01,363.0,408.0,-45.0,0.0,45.0,-45.0,0
2,2026-03-01 → 2026-04-01,408.0,396.0,12.0,87.0,75.0,-75.0,0
3,2026-04-01 → 2026-05-01,396.0,377.0,19.0,23.0,4.0,-4.0,0
4,2026-05-01 → 2026-06-01,377.0,403.0,-26.0,39.0,65.0,-65.0,3
5,2026-06-01 → 2026-07-01,403.0,392.0,11.0,31.0,20.0,-20.0,1

,codigo,stock_inicial,stock_final,desviacion_snapshots,consumo_facturado,veces_en_cero,inventario_promedio,unidades_pactadas,inventario_medio_vs_pactado,senal
3,400300SKF,3.0,3.0,0.0,5.0,0,3.0,6,0.5,STOCK_PLANO_COMPATIBLE_REPOSICION_SEMANAL
82,6312-2RS1/C3GJNSKF,4.0,4.0,0.0,3.0,0,4.0,4,1.0,STOCK_PLANO_COMPATIBLE_REPOSICION_SEMANAL
92,6316-2RS1/C3SKF,0.0,0.0,0.0,1.0,7,0.0,3,0.0,VENTA_SIN_CRUCE_INVENTARIO
94,6316/C3SKF,0.0,0.0,0.0,8.0,7,0.0,2,0.0,VENTA_SIN_CRUCE_INVENTARIO

## Bloque B — ¿Se usa lo que está en la bodega?

La rotación se anualiza según los días realmente observados entre el primer y último
snapshot. El capital usa unidades físicas y costo promedio del snapshot más reciente.

In [4]:
days_observed = max((end - start).days, 1)
annual_factor = 365.25 / days_observed
latest_date = inventario["fecha_snapshot"].max()
latest = (
    inventario[inventario["fecha_snapshot"].eq(latest_date)]
    .sort_values("fecha_carga").drop_duplicates("idproducto", keep="last")
    .set_index("idproducto")
)
with sqlite3.connect(uri, uri=True) as con:
    costos_inventario = pd.read_sql_query(
        "SELECT idproducto, costo_unitario, fecha_snapshot, fecha_carga "
        "FROM inventario_snapshot WHERE costo_unitario IS NOT NULL", con,
    )
    costos_ventas = pd.read_sql_query(
        "SELECT idproducto, costo, fecha FROM raw_sales WHERE costo IS NOT NULL", con,
    )
costos_inventario["fecha_snapshot"] = pd.to_datetime(
    costos_inventario["fecha_snapshot"], errors="coerce"
)
costo_inv_actual = (
    costos_inventario.sort_values(["fecha_snapshot", "fecha_carga"])
    .drop_duplicates("idproducto", keep="last").set_index("idproducto")["costo_unitario"]
)
costos_ventas["fecha"] = pd.to_datetime(costos_ventas["fecha"], errors="coerce")
costo_venta_reciente = (
    costos_ventas.sort_values("fecha").drop_duplicates("idproducto", keep="last")
    .set_index("idproducto")["costo"]
)
avg_inventory = inventario.groupby("idproducto")["unidades"].mean()
first_inventory = (
    inventario[inventario["fecha_snapshot"].eq(start)]
    .groupby("idproducto")["unidades"].sum()
)
last_inventory = (
    inventario[inventario["fecha_snapshot"].eq(end)]
    .groupby("idproducto")["unidades"].sum()
)

uso = acuerdo[["codigo", "unidades_pactadas"]].copy()
uso["consumo_periodo"] = uso["codigo"].map(ventas_por_codigo).fillna(0)
uso["consumo_anualizado"] = uso["consumo_periodo"] * annual_factor
uso["inventario_promedio"] = uso["codigo"].map(avg_inventory).fillna(0)
uso["rotaciones_anualizadas"] = np.where(
    uso["inventario_promedio"] > 0,
    uso["consumo_anualizado"] / uso["inventario_promedio"], np.nan,
)
uso["inventario_inicial"] = uso["codigo"].map(first_inventory).fillna(0)
uso["inventario_final"] = uso["codigo"].map(last_inventory).fillna(0)
uso["inventario_sin_cambio"] = uso["inventario_inicial"].eq(uso["inventario_final"])
uso["costo_actual"] = uso["codigo"].map(costo_inv_actual)
uso["fuente_costo_actual"] = np.where(
    uso["costo_actual"].notna(), "ÚLTIMO_SNAPSHOT_EMPRESA", "ÚLTIMA_VENTA"
)
uso["costo_actual"] = uso["costo_actual"].fillna(
    uso["codigo"].map(costo_venta_reciente)
)
assert uso["costo_actual"].notna().all(), "Hay referencias pactadas sin costo actual"
uso["capital_comprometido_ref"] = (
    uso["unidades_pactadas"] * uso["costo_actual"]
)
display(uso.sort_values("rotaciones_anualizadas", na_position="first"))

capital_total = uso["capital_comprometido_ref"].sum()
capital_lento = uso.loc[
    uso["rotaciones_anualizadas"].fillna(0).lt(1), "capital_comprometido_ref"
].sum()
print(
    "Capital comprometido en referencias con rotación < 1x/año:",
    PESO(capital_lento),
    f"({capital_lento / capital_total:.1%} del capital del acuerdo)"
    if capital_total else "(sin capital)",
)

,codigo,unidades_pactadas,consumo_periodo,consumo_anualizado,inventario_promedio,rotaciones_anualizadas,inventario_inicial,inventario_final,inventario_sin_cambio,costo_actual,fuente_costo_actual,capital_comprometido_ref
20,6006-2Z/C3GJNSKF,1,0.0,0.000000,0.000000,NaN,0.0,0.0,True,18111.792858,ÚLTIMO_SNAPSHOT_EMPRESA,1.811179e+04
44,6211-2RS1/C3SKF,1,0.0,0.000000,0.000000,NaN,0.0,0.0,True,78150.389275,ÚLTIMO_SNAPSHOT_EMPRESA,7.815039e+04
45,6211-2Z/C3SKF,4,0.0,0.000000,0.000000,NaN,0.0,0.0,True,66096.557964,ÚLTIMO_SNAPSHOT_EMPRESA,2.643862e+05
48,6213-2RS1/C3GJNSKF,4,0.0,0.000000,0.000000,NaN,0.0,0.0,True,131629.311885,ÚLTIMO_SNAPSHOT_EMPRESA,5.265172e+05
51,6213-2Z/C3SKF,1,0.0,0.000000,0.000000,NaN,0.0,0.0,True,177091.103000,ÚLTIMA_VENTA,1.770911e+05
52,6214-2RS1/C3SKF,4,0.0,0.000000,0.000000,NaN,0.0,0.0,True,134649.659619,ÚLTIMO_SNAPSHOT_EMPRESA,5.385986e+05
53,6214-2Z/C3SKF,3,0.0,0.000000,0.000000,NaN,0.0,0.0,True,176032.240775,ÚLTIMO_SNAPSHOT_EMPRESA,5.280967e+05
54,6215-2RS1/C3SKF,5,0.0,0.000000,0.000000,NaN,0.0,0.0,True,223831.914905,ÚLTIMO_SNAPSHOT_EMPRESA,1.119160e+06
56,6216-2Z/C3SKF,2,0.0,0.000000,0.000000,NaN,0.0,0.0,True,203232.368893,ÚLTIMO_SNAPSHOT_EMPRESA,4.064647e+05
58,6218-2Z/C3SKF,1,0.0,0.000000,0.000000,NaN,0.0,0.0,True,467499.007682,ÚLTIMO_SNAPSHOT_EMPRESA,4.674990e+05
60,6300-2Z/C3SKF,4,0.0,0.000000,0.000000,NaN,0.0,0.0,True,1509.891378,ÚLTIMO_SNAPSHOT_EMPRESA,6.039566e+03
63,6303-2RSH/C3GJNSKF,2,0.0,0.000000,0.000000,NaN,0.0,0.0,True,11950.688948,ÚLTIMO_SNAPSHOT_EMPRESA,2.390138e+04
64,6303-2Z/C3GJNSKF,2,0.0,0.000000,0.000000,NaN,0.0,0.0,True,11804.535053,ÚLTIMO_SNAPSHOT_EMPRESA,2.360907e+04
78,6310-2RS1/C3SKF,4,0.0,0.000000,0.000000,NaN,0.0,0.0,True,91572.235479,ÚLTIMO_SNAPSHOT_EMPRESA,3.662889e+05
86,6313-2Z/C3SKF,1,0.0,0.000000,0.000000,NaN,0.0,0.0,True,201144.689789,ÚLTIMO_SNAPSHOT_EMPRESA,2.011447e+05
89,6314-2Z/C3SKF,4,0.0,0.000000,0.000000,NaN,0.0,0.0,True,481576.000000,ÚLTIMA_VENTA,1.926304e+06
92,6316-2RS1/C3SKF,3,1.0,2.017956,0.000000,NaN,0.0,0.0,True,496143.361597,ÚLTIMO_SNAPSHOT_EMPRESA,1.488430e+06
93,6316-2Z/C3SKF,2,0.0,0.000000,0.000000,NaN,0.0,0.0,True,320505.189355,ÚLTIMO_SNAPSHOT_EMPRESA,6.410104e+05
94,6316/C3SKF,2,8.0,16.143646,0.000000,NaN,0.0,0.0,True,506665.980392,ÚLTIMO_SNAPSHOT_EMPRESA,1.013332e+06
95,6319/C3SKF,2,0.0,0.000000,0.000000,NaN,0.0,0.0,True,524357.983629,ÚLTIMO_SNAPSHOT_EMPRESA,1.048716e+06
96,7312 BECBJSKF,2,0.0,0.000000,0.000000,NaN,0.0,0.0,True,269135.356800,ÚLTIMO_SNAPSHOT_EMPRESA,5.382707e+05
97,99235SKF,2,0.0,0.000000,0.000000,NaN,0.0,0.0,True,47180.286283,ÚLTIMO_SNAPSHOT_EMPRESA,9.436057e+04
98,NJ 220 ECJ/C3SKF,1,0.0,0.000000,0.000000,NaN,0.0,0.0,True,516605.822100,ÚLTIMO_SNAPSHOT_EMPRESA,5.166058e+05
99,NU 2211 ECP/C3SKF,1,0.0,0.000000,0.000000,NaN,0.0,0.0,True,33647.458110,ÚLTIMO_SNAPSHOT_EMPRESA,3.364746e+04
91,6315-2Z/C3GJNSKF,3,0.0,0.000000,3.000000,0.000000,3.0,3.0,True,369881.959559,ÚLTIMO_SNAPSHOT_EMPRESA,1.109646e+06
24,6201-2RSH/C3GJNSKF,5,0.0,0.000000,3.000000,0.000000,3.0,3.0,True,8042.268349,ÚLTIMO_SNAPSHOT_EMPRESA,4.021134e+04
22,6008-2Z/C3GJNSKF,2,0.0,0.000000,2.000000,0.000000,2.0,2.0,True,30864.678650,ÚLTIMO_SNAPSHOT_EMPRESA,6.172936e+04
21,6007-2RS1/C3GJNSKF,9,0.0,0.000000,8.000000,0.000000,8.0,8.0,True,21686.466194,ÚLTIMO_SNAPSHOT_EMPRESA,1.951782e+05
19,6005-2Z/C3GJNSKF,10,0.0,0.000000,10.000000,0.000000,10.0,10.0,True,11909.986291,ÚLTIMO_SNAPSHOT_EMPRESA,1.190999e+05
17,6004-2Z/C3GJNSKF,10,0.0,0.000000,1.000000,0.000000,1.0,1.0,True,10249.900614,ÚLTIMO_SNAPSHOT_EMPRESA,1.024990e+05
49,6213-2RS1/C3SKF,2,0.0,0.000000,2.000000,0.000000,2.0,2.0,True,127499.945364,ÚLTIMO_SNAPSHOT_EMPRESA,2.549999e+05
50,6213-2Z/C3GJNSKF,8,0.0,0.000000,4.000000,0.000000,4.0,4.0,True,126997.463231,ÚLTIMO_SNAPSHOT_EMPRESA,1.015980e+06
39,6209-2RS1/C3GJNSKF,3,0.0,0.000000,8.000000,0.000000,8.0,8.0,True,45003.865938,ÚLTIMO_SNAPSHOT_EMPRESA,1.350116e+05
12,400750SKF,5,0.0,0.000000,2.000000,0.000000,2.0,2.0,True,36680.171194,ÚLTIMO_SNAPSHOT_EMPRESA,1.834009e+05
57,6217-2Z/C3SKF,2,0.0,0.000000,1.000000,0.000000,1.0,1.0,True,268903.535791,ÚLTIMO_SNAPSHOT_EMPRESA,5.378071e+05
55,6215-2Z/C3GJNSKF,2,0.0,0.000000,1.000000,0.000000,1.0,1.0,True,178681.580369,ÚLTIMO_SNAPSHOT_EMPRESA,3.573632e+05
62,6302-2Z/C3GJNSKF,6,0.0,0.000000,6.000000,0.000000,6.0,6.0,True,10964.857394,ÚLTIMO_SNAPSHOT_EMPRESA,6.578914e+04
65,6304-2RSH/C3GJNSKF,4,0.0,0.000000,4.000000,0.000000,4.0,4.0,True,15716.470023,ÚLTIMO_SNAPSHOT_EMPRESA,6.286588e+04
66,6304-2Z/C3GJNSKF,4,0.0,0.000000,3.428571,0.000000,2.0,7.0,False,14544.517605,ÚLTIMO_SNAPSHOT_EMPRESA,5.817807e+04
67,6305-2RS1/C3GJNSKF,3,0.0,0.000000,7.000000,0.000000,7.0,7.0,True,22858.383981,ÚLTIMO_SNAPSHOT_EMPRESA,6.857515e+04
72,6307-2Z/C3GJNSKF,4,0.0,0.000000,3.000000,0.000000,3.0,3.0,True,42910.245652,ÚLTIMO_SNAPSHOT_EMPRESA,1.716410e+05
2,400250SKF,9,0.0,0.000000,2.000000,0.000000,2.0,2.0,True,23346.217663,ÚLTIMO_SNAPSHOT_EMPRESA,2.101160e+05
1,400200SKF,10,0.0,0.000000,4.000000,0.000000,4.0,4.0,True,6912.320684,ÚLTIMO_SNAPSHOT_EMPRESA,6.912321e+04
61,6302-2RSH/C3GJNSKF,4,0.0,0.000000,1.000000,0.000000,1.0,1.0,True,14258.858066,ÚLTIMO_SNAPSHOT_EMPRESA,5.703543e+04
27,6202-2Z/C3GJNSKF,7,0.0,0.000000,11.000000,0.000000,11.0,11.0,True,7397.151014,ÚLTIMO_SNAPSHOT_EMPRESA,5.178006e+04
18,6005-2RSH/C3GJNSKF,10,1.0,2.017956,9.571429,0.210831,10.0,9.0,False,14727.989585,ÚLTIMO_SNAPSHOT_EMPRESA,1.472799e+05
46,6212-2RS1/C3GJNSKF,5,1.0,2.017956,6.428571,0.313904,3.0,7.0,False,84098.509116,ÚLTIMO_SNAPSHOT_EMPRESA,4.204925e+05
68,6305-2Z/C3GJNSKF,2,1.0,2.017956,5.000000,0.403591,3.0,7.0,False,21374.130873,ÚLTIMO_SNAPSHOT_EMPRESA,4.274826e+04
25,6201-2Z/C3GJNSKF,6,1.0,2.017956,4.428571,0.455667,5.0,4.0,False,7192.579480,ÚLTIMO_SNAPSHOT_EMPRESA,4.315548e+04
7,400500SKF,2,2.0,4.035912,6.285714,0.642077,8.0,6.0,False,24446.298858,ÚLTIMO_SNAPSHOT_EMPRESA,4.889260e+04
41,6210-2RS1/C3GJNSKF,6,2.0,4.035912,6.285714,0.642077,8.0,6.0,False,55400.875936,ÚLTIMO_SNAPSHOT_EMPRESA,3.324053e+05
0,400160SKF,3,1.0,2.017956,2.714286,0.743457,3.0,2.0,False,19936.871062,ÚLTIMO_SNAPSHOT_EMPRESA,5.981061e+04
30,6204-2RSH/C3GJNSKF,7,2.0,4.035912,4.857143,0.830923,3.0,6.0,False,10964.644632,ÚLTIMO_SNAPSHOT_EMPRESA,7.675251e+04
26,6202-2RSH/C3GJNSKF,18,6.0,12.107735,13.571429,0.892149,18.0,10.0,False,9014.954232,ÚLTIMO_SNAPSHOT_EMPRESA,1.622692e+05
43,6211-2RS1/C3GJNSKF,5,2.0,4.035912,4.285714,0.941713,5.0,3.0,False,75359.664812,ÚLTIMO_SNAPSHOT_EMPRESA,3.767983e+05
87,6314-2RS1/C3GJNSKF,4,1.0,2.017956,2.142857,0.941713,3.0,2.0,False,328238.276773,ÚLTIMO_SNAPSHOT_EMPRESA,1.312953e+06
47,6212-2Z/C3GJNSKF,4,3.0,6.053867,6.000000,1.008978,4.0,6.0,False,83849.419557,ÚLTIMO_SNAPSHOT_EMPRESA,3.353977e+05
16,401000SKF,1,2.0,4.035912,4.000000,1.008978,0.0,3.0,False,50985.857745,ÚLTIMO_SNAPSHOT_EMPRESA,5.098586e+04
42,6210-2Z/C3GJNSKF,9,3.0,6.053867,6.000000,1.008978,4.0,6.0,False,50800.748290,ÚLTIMO_SNAPSHOT_EMPRESA,4.572067e+05
70,6306-2Z/C3GJNSKF,6,2.0,4.035912,4.000000,1.008978,5.0,3.0,False,26503.943379,ÚLTIMO_SNAPSHOT_EMPRESA,1.590237e+05
36,6207-2Z/C3GJNSKF,5,3.0,6.053867,5.285714,1.145326,4.0,6.0,False,26353.484876,ÚLTIMO_SNAPSHOT_EMPRESA,1.317674e+05
80,6311-2RS1/C3GJNSKF,3,2.0,4.035912,3.428571,1.177141,3.0,5.0,False,136247.746680,ÚLTIMO_SNAPSHOT_EMPRESA,4.087432e+05
59,6300-2RSH/C3GJNSKF,5,1.0,2.017956,1.571429,1.284154,2.0,1.0,False,13316.851727,ÚLTIMO_SNAPSHOT_EMPRESA,6.658426e+04
35,6207-2RS1/C3GJNSKF,9,4.0,8.071823,6.142857,1.314018,7.0,8.0,False,27857.504629,ÚLTIMO_SNAPSHOT_EMPRESA,2.507175e+05
32,6205-2RSH/C3GJNSKF,5,6.0,12.107735,9.142857,1.324283,6.0,10.0,False,13144.471911,ÚLTIMO_SNAPSHOT_EMPRESA,6.572236e+04
5,400400SKF,4,5.0,10.089779,7.428571,1.358239,7.0,7.0,True,27332.947672,ÚLTIMO_SNAPSHOT_EMPRESA,1.093318e+05
28,6203-2RSH/C3GJNSKF,4,5.0,10.089779,7.000000,1.441397,4.0,9.0,False,9847.353939,ÚLTIMO_SNAPSHOT_EMPRESA,3.938942e+04
71,6307-2RS1/C3GJNSKF,8,3.0,6.053867,4.000000,1.513467,4.0,6.0,False,44212.908828,ÚLTIMO_SNAPSHOT_EMPRESA,3.537033e+05
82,6312-2RS1/C3GJNSKF,4,3.0,6.053867,4.000000,1.513467,4.0,4.0,True,193466.219373,ÚLTIMO_SNAPSHOT_EMPRESA,7.738649e+05
11,400700SKF,4,3.0,6.053867,4.000000,1.513467,6.0,3.0,False,37844.753942,ÚLTIMO_SNAPSHOT_EMPRESA,1.513790e+05
85,6313-2Z/C3GJNSKF,2,3.0,6.053867,3.714286,1.629887,2.0,4.0,False,235416.602803,ÚLTIMO_SNAPSHOT_EMPRESA,4.708332e+05
31,6204-2Z/C3GJNSKF,10,6.0,12.107735,7.285714,1.661846,11.0,5.0,False,9776.570388,ÚLTIMO_SNAPSHOT_EMPRESA,9.776570e+04
13,400800SKF,3,3.0,6.053867,3.571429,1.695083,5.0,2.0,False,39440.340840,ÚLTIMO_SNAPSHOT_EMPRESA,1.183210e+05
73,6308-2RS1/C3GJNSKF,7,4.0,8.071823,4.714286,1.712205,1.0,7.0,False,53198.037247,ÚLTIMO_SNAPSHOT_EMPRESA,3.723863e+05
38,6208-2Z/C3GJNSKF,5,6.0,12.107735,7.000000,1.729676,9.0,8.0,False,34336.319368,ÚLTIMO_SNAPSHOT_EMPRESA,1.716816e+05
77,6310-2RS1/C3GJNSKF,4,4.0,8.071823,4.428571,1.822670,5.0,6.0,False,117235.067506,ÚLTIMO_SNAPSHOT_EMPRESA,4.689403e+05
14,400850SKF,5,3.0,6.053867,3.000000,2.017956,5.0,2.0,False,32776.889632,ÚLTIMO_SNAPSHOT_EMPRESA,1.638844e+05
90,6315-2RS1/C3GJNSKF,3,1.0,2.017956,1.000000,2.017956,0.0,1.0,False,415145.566421,ÚLTIMO_SNAPSHOT_EMPRESA,1.245437e+06
74,6308-2Z/C3GJNSKF,8,5.0,10.089779,4.857143,2.077307,4.0,4.0,True,46474.057440,ÚLTIMO_SNAPSHOT_EMPRESA,3.717925e+05
4,400350SKF,8,4.0,8.071823,3.857143,2.092695,6.0,2.0,False,28334.503615,ÚLTIMO_SNAPSHOT_EMPRESA,2.266760e+05
69,6306-2RS1/C3GJNSKF,4,8.0,16.143646,7.571429,2.132180,5.0,7.0,False,30445.999576,ÚLTIMO_SNAPSHOT_EMPRESA,1.217840e+05
6,400450SKF,4,5.0,10.089779,4.428571,2.278337,7.0,2.0,False,19591.161768,ÚLTIMO_SNAPSHOT_EMPRESA,7.836465e+04
15,400900SKF,4,4.0,8.071823,3.285714,2.456642,2.0,4.0,False,68956.707540,ÚLTIMO_SNAPSHOT_EMPRESA,2.758268e+05
88,6314-2Z/C3GJNSKF,2,3.0,6.053867,2.285714,2.648567,4.0,1.0,False,291877.416996,ÚLTIMO_SNAPSHOT_EMPRESA,5.837548e+05
34,6206-2Z/C3GJNSKF,5,8.0,16.143646,6.000000,2.690608,5.0,7.0,False,20017.007928,ÚLTIMO_SNAPSHOT_EMPRESA,1.000850e+05
10,400650SKF,5,5.0,10.089779,3.714286,2.716479,5.0,3.0,False,37079.122211,ÚLTIMO_SNAPSHOT_EMPRESA,1.853956e+05
23,6200-2Z/C3GJNSKF,4,6.0,12.107735,4.285714,2.825138,7.0,1.0,False,7018.523796,ÚLTIMO_SNAPSHOT_EMPRESA,2.807410e+04
76,6309-2Z/C3GJNSKF,5,6.0,12.107735,4.285714,2.825138,6.0,5.0,False,56720.386884,ÚLTIMO_SNAPSHOT_EMPRESA,2.836019e+05
40,6209-2Z/C3GJNSKF,6,10.0,20.179558,6.714286,3.005466,10.0,10.0,True,40632.237424,ÚLTIMO_SNAPSHOT_EMPRESA,2.437934e+05
33,6205-2Z/C3GJNSKF,8,6.0,12.107735,4.000000,3.026934,3.0,2.0,False,11317.949921,ÚLTIMO_SNAPSHOT_EMPRESA,9.054360e+04
75,6309-2RS1/C3GJNSKF,11,9.0,18.161602,5.571429,3.259775,5.0,6.0,False,75052.900132,ÚLTIMO_SNAPSHOT_EMPRESA,8.255819e+05
84,6313-2RS1/C3GJNSKF,5,4.0,8.071823,2.428571,3.323692,1.0,2.0,False,248589.074802,ÚLTIMO_SNAPSHOT_EMPRESA,1.242945e+06
3,400300SKF,6,5.0,10.089779,3.000000,3.363260,3.0,3.0,True,21996.498717,ÚLTIMO_SNAPSHOT_EMPRESA,1.319790e+05
37,6208-2RS1/C3GJNSKF,6,7.0,14.125691,4.142857,3.409649,1.0,4.0,False,37642.332709,ÚLTIMO_SNAPSHOT_EMPRESA,2.258540e+05
29,6203-2Z/C3GJNSKF,6,16.0,32.287293,7.714286,4.185390,11.0,10.0,False,8458.906402,ÚLTIMO_SNAPSHOT_EMPRESA,5.075344e+04
83,6312-2Z/C3GJNSKF,4,8.0,16.143646,3.714286,4.346366,1.0,5.0,False,169452.741710,ÚLTIMO_SNAPSHOT_EMPRESA,6.778110e+05
79,6310-2Z/C3GJNSKF,9,9.0,18.161602,4.142857,4.383835,6.0,2.0,False,99078.569482,ÚLTIMO_SNAPSHOT_EMPRESA,8.917071e+05
8,400550SKF,2,6.0,12.107735,2.714286,4.460744,2.0,1.0,False,37162.868071,ÚLTIMO_SNAPSHOT_EMPRESA,7.432574e+04
81,6311-2Z/C3GJNSKF,5,10.0,20.179558,3.857143,5.231737,2.0,2.0,True,119411.143397,ÚLTIMO_SNAPSHOT_EMPRESA,5.970557e+05
9,400600SKF,1,7.0,14.125691,1.857143,7.606141,3.0,1.0,False,12323.745173,ÚLTIMO_SNAPSHOT_EMPRESA,1.232375e+04

Capital comprometido en referencias con rotación < 1x/año: $19,997,324 (59.2% del capital del acuerdo)

## Bloque C — ¿Es correcta la cantidad pactada?

El nivel diagnóstico equivale a 2,5 meses de consumo anualizado, redondeado hacia arriba
a número par. El veredicto se decide exclusivamente por la cobertura del nivel pactado:
menos de 2 meses implica **SUBIR**, entre 2 y 8 meses **MANTENER**, y más de 8 meses
**BAJAR**. El consumo cero conserva el corte duro **RETIRAR**.

El inventario observado y los snapshots en cero no participan en esta decisión porque
la reposición semanal tiende a devolver el stock al nivel pactado.

In [5]:
monthly_factor = 12 * days_observed / 365.25
monthly_factor = max(monthly_factor, 1)
metricas = uso.copy()
metricas["consumo_mensual"] = metricas["consumo_periodo"] / monthly_factor
metricas["meses_cobertura"] = np.where(
    metricas["consumo_mensual"] > 0,
    metricas["unidades_pactadas"] / metricas["consumo_mensual"], np.nan,
)
metricas["nivel_simple"] = (
    metricas["consumo_mensual"] * MESES_COBERTURA_OBJETIVO
).map(ceil_even)
metricas["veces_en_cero"] = metricas["codigo"].map(zero_counts).fillna(
    len(fechas_snapshot)
).astype(int)
metricas["inventario_maximo"] = metricas["codigo"].map(
    acuerdo_stock.max(axis=1)
).fillna(0)
metricas["inventario_medio_vs_pactado"] = np.where(
    metricas["unidades_pactadas"] > 0,
    metricas["inventario_promedio"] / metricas["unidades_pactadas"], np.nan,
)

def verdict(row):
    if row["consumo_periodo"] <= 0:
        return "RETIRAR"
    if row["meses_cobertura"] < COBERTURA_BAJA_MESES:
        return "SUBIR"
    if row["meses_cobertura"] > COBERTURA_ALTA_MESES:
        return "BAJAR"
    return "MANTENER"

def reason(row):
    if row["veredicto"] == "RETIRAR":
        return (
            f"Sin consumo entre {start:%Y-%m-%d} y {end:%Y-%m-%d}; "
            "retiro por corte duro de consumo cero."
        )
    if row["veredicto"] == "SUBIR":
        return (
            f"Cobertura pactada {row['meses_cobertura']:.2f} meses, menor que "
            f"el umbral de {COBERTURA_BAJA_MESES:.0f} meses."
        )
    if row["veredicto"] == "BAJAR":
        return (
            f"Cobertura pactada {row['meses_cobertura']:.2f} meses, mayor que "
            f"el umbral de {COBERTURA_ALTA_MESES:.0f} meses."
        )
    return (
        f"Cobertura pactada {row['meses_cobertura']:.2f} meses, dentro del "
        f"rango de {COBERTURA_BAJA_MESES:.0f} a "
        f"{COBERTURA_ALTA_MESES:.0f} meses."
    )

metricas["veredicto"] = metricas.apply(verdict, axis=1)
metricas["motivo"] = metricas.apply(reason, axis=1)
metricas["unidades_propuestas"] = np.select(
    [
        metricas["veredicto"].eq("RETIRAR"),
        metricas["veredicto"].isin(["BAJAR", "SUBIR"]),
    ],
    [0, metricas["nivel_simple"]],
    default=metricas["unidades_pactadas"],
).astype(int)
metricas["capital_propuesto_ref"] = (
    metricas["unidades_propuestas"] * metricas["costo_actual"]
)
display(
    metricas.sort_values(
        ["veredicto", "capital_comprometido_ref"], ascending=[True, False]
    )
)

,codigo,unidades_pactadas,consumo_periodo,consumo_anualizado,inventario_promedio,rotaciones_anualizadas,inventario_inicial,inventario_final,inventario_sin_cambio,costo_actual,fuente_costo_actual,capital_comprometido_ref,consumo_mensual,meses_cobertura,nivel_simple,veces_en_cero,inventario_maximo,inventario_medio_vs_pactado,veredicto,motivo,unidades_propuestas,capital_propuesto_ref
92,6316-2RS1/C3SKF,3,1.0,2.017956,0.000000,NaN,0.0,0.0,True,496143.361597,ÚLTIMO_SNAPSHOT_EMPRESA,1.488430e+06,0.168163,17.839836,1,7,0.0,0.000000,BAJAR,"Cobertura pactada 17.84 meses, mayor que el um...",1,4.961434e+05
87,6314-2RS1/C3GJNSKF,4,1.0,2.017956,2.142857,0.941713,3.0,2.0,False,328238.276773,ÚLTIMO_SNAPSHOT_EMPRESA,1.312953e+06,0.168163,23.786448,1,0,3.0,0.535714,BAJAR,"Cobertura pactada 23.79 meses, mayor que el um...",1,3.282383e+05
90,6315-2RS1/C3GJNSKF,3,1.0,2.017956,1.000000,2.017956,0.0,1.0,False,415145.566421,ÚLTIMO_SNAPSHOT_EMPRESA,1.245437e+06,0.168163,17.839836,1,1,1.0,0.333333,BAJAR,"Cobertura pactada 17.84 meses, mayor que el um...",1,4.151456e+05
42,6210-2Z/C3GJNSKF,9,3.0,6.053867,6.000000,1.008978,4.0,6.0,False,50800.748290,ÚLTIMO_SNAPSHOT_EMPRESA,4.572067e+05,0.504489,17.839836,2,0,7.0,0.666667,BAJAR,"Cobertura pactada 17.84 meses, mayor que el um...",2,1.016015e+05
46,6212-2RS1/C3GJNSKF,5,1.0,2.017956,6.428571,0.313904,3.0,7.0,False,84098.509116,ÚLTIMO_SNAPSHOT_EMPRESA,4.204925e+05,0.168163,29.733060,1,0,7.0,1.285714,BAJAR,"Cobertura pactada 29.73 meses, mayor que el um...",1,8.409851e+04
80,6311-2RS1/C3GJNSKF,3,2.0,4.035912,3.428571,1.177141,3.0,5.0,False,136247.746680,ÚLTIMO_SNAPSHOT_EMPRESA,4.087432e+05,0.336326,8.919918,1,0,6.0,1.142857,BAJAR,"Cobertura pactada 8.92 meses, mayor que el umb...",1,1.362477e+05
43,6211-2RS1/C3GJNSKF,5,2.0,4.035912,4.285714,0.941713,5.0,3.0,False,75359.664812,ÚLTIMO_SNAPSHOT_EMPRESA,3.767983e+05,0.336326,14.866530,1,0,5.0,0.857143,BAJAR,"Cobertura pactada 14.87 meses, mayor que el um...",1,7.535966e+04
73,6308-2RS1/C3GJNSKF,7,4.0,8.071823,4.714286,1.712205,1.0,7.0,False,53198.037247,ÚLTIMO_SNAPSHOT_EMPRESA,3.723863e+05,0.672652,10.406571,2,0,7.0,0.673469,BAJAR,"Cobertura pactada 10.41 meses, mayor que el um...",2,1.063961e+05
74,6308-2Z/C3GJNSKF,8,5.0,10.089779,4.857143,2.077307,4.0,4.0,True,46474.057440,ÚLTIMO_SNAPSHOT_EMPRESA,3.717925e+05,0.840815,9.514579,4,0,7.0,0.607143,BAJAR,"Cobertura pactada 9.51 meses, mayor que el umb...",4,1.858962e+05
71,6307-2RS1/C3GJNSKF,8,3.0,6.053867,4.000000,1.513467,4.0,6.0,False,44212.908828,ÚLTIMO_SNAPSHOT_EMPRESA,3.537033e+05,0.504489,15.857632,2,0,6.0,0.500000,BAJAR,"Cobertura pactada 15.86 meses, mayor que el um...",2,8.842582e+04
41,6210-2RS1/C3GJNSKF,6,2.0,4.035912,6.285714,0.642077,8.0,6.0,False,55400.875936,ÚLTIMO_SNAPSHOT_EMPRESA,3.324053e+05,0.336326,17.839836,1,0,8.0,1.047619,BAJAR,"Cobertura pactada 17.84 meses, mayor que el um...",1,5.540088e+04
35,6207-2RS1/C3GJNSKF,9,4.0,8.071823,6.142857,1.314018,7.0,8.0,False,27857.504629,ÚLTIMO_SNAPSHOT_EMPRESA,2.507175e+05,0.672652,13.379877,2,0,8.0,0.682540,BAJAR,"Cobertura pactada 13.38 meses, mayor que el um...",2,5.571501e+04
4,400350SKF,8,4.0,8.071823,3.857143,2.092695,6.0,2.0,False,28334.503615,ÚLTIMO_SNAPSHOT_EMPRESA,2.266760e+05,0.672652,11.893224,2,0,6.0,0.482143,BAJAR,"Cobertura pactada 11.89 meses, mayor que el um...",2,5.666901e+04
14,400850SKF,5,3.0,6.053867,3.000000,2.017956,5.0,2.0,False,32776.889632,ÚLTIMO_SNAPSHOT_EMPRESA,1.638844e+05,0.504489,9.911020,2,0,5.0,0.600000,BAJAR,"Cobertura pactada 9.91 meses, mayor que el umb...",2,6.555378e+04
26,6202-2RSH/C3GJNSKF,18,6.0,12.107735,13.571429,0.892149,18.0,10.0,False,9014.954232,ÚLTIMO_SNAPSHOT_EMPRESA,1.622692e+05,1.008978,17.839836,4,0,18.0,0.753968,BAJAR,"Cobertura pactada 17.84 meses, mayor que el um...",4,3.605982e+04
70,6306-2Z/C3GJNSKF,6,2.0,4.035912,4.000000,1.008978,5.0,3.0,False,26503.943379,ÚLTIMO_SNAPSHOT_EMPRESA,1.590237e+05,0.336326,17.839836,1,0,5.0,0.666667,BAJAR,"Cobertura pactada 17.84 meses, mayor que el um...",1,2.650394e+04
18,6005-2RSH/C3GJNSKF,10,1.0,2.017956,9.571429,0.210831,10.0,9.0,False,14727.989585,ÚLTIMO_SNAPSHOT_EMPRESA,1.472799e+05,0.168163,59.466119,1,0,10.0,0.957143,BAJAR,"Cobertura pactada 59.47 meses, mayor que el um...",1,1.472799e+04
36,6207-2Z/C3GJNSKF,5,3.0,6.053867,5.285714,1.145326,4.0,6.0,False,26353.484876,ÚLTIMO_SNAPSHOT_EMPRESA,1.317674e+05,0.504489,9.911020,2,0,7.0,1.057143,BAJAR,"Cobertura pactada 9.91 meses, mayor que el umb...",2,5.270697e+04
31,6204-2Z/C3GJNSKF,10,6.0,12.107735,7.285714,1.661846,11.0,5.0,False,9776.570388,ÚLTIMO_SNAPSHOT_EMPRESA,9.776570e+04,1.008978,9.911020,4,0,11.0,0.728571,BAJAR,"Cobertura pactada 9.91 meses, mayor que el umb...",4,3.910628e+04
30,6204-2RSH/C3GJNSKF,7,2.0,4.035912,4.857143,0.830923,3.0,6.0,False,10964.644632,ÚLTIMO_SNAPSHOT_EMPRESA,7.675251e+04,0.336326,20.813142,1,0,6.0,0.693878,BAJAR,"Cobertura pactada 20.81 meses, mayor que el um...",1,1.096464e+04
59,6300-2RSH/C3GJNSKF,5,1.0,2.017956,1.571429,1.284154,2.0,1.0,False,13316.851727,ÚLTIMO_SNAPSHOT_EMPRESA,6.658426e+04,0.168163,29.733060,1,0,2.0,0.314286,BAJAR,"Cobertura pactada 29.73 meses, mayor que el um...",1,1.331685e+04
0,400160SKF,3,1.0,2.017956,2.714286,0.743457,3.0,2.0,False,19936.871062,ÚLTIMO_SNAPSHOT_EMPRESA,5.981061e+04,0.168163,17.839836,1,0,3.0,0.904762,BAJAR,"Cobertura pactada 17.84 meses, mayor que el um...",1,1.993687e+04
25,6201-2Z/C3GJNSKF,6,1.0,2.017956,4.428571,0.455667,5.0,4.0,False,7192.579480,ÚLTIMO_SNAPSHOT_EMPRESA,4.315548e+04,0.168163,35.679671,1,0,5.0,0.738095,BAJAR,"Cobertura pactada 35.68 meses, mayor que el um...",1,7.192579e+03
68,6305-2Z/C3GJNSKF,2,1.0,2.017956,5.000000,0.403591,3.0,7.0,False,21374.130873,ÚLTIMO_SNAPSHOT_EMPRESA,4.274826e+04,0.168163,11.893224,1,0,7.0,2.500000,BAJAR,"Cobertura pactada 11.89 meses, mayor que el um...",1,2.137413e+04
84,6313-2RS1/C3GJNSKF,5,4.0,8.071823,2.428571,3.323692,1.0,2.0,False,248589.074802,ÚLTIMO_SNAPSHOT_EMPRESA,1.242945e+06,0.672652,7.433265,2,0,4.0,0.485714,MANTENER,"Cobertura pactada 7.43 meses, dentro del rango...",5,1.242945e+06
79,6310-2Z/C3GJNSKF,9,9.0,18.161602,4.142857,4.383835,6.0,2.0,False,99078.569482,ÚLTIMO_SNAPSHOT_EMPRESA,8.917071e+05,1.513467,5.946612,4,0,6.0,0.460317,MANTENER,"Cobertura pactada 5.95 meses, dentro del rango...",9,8.917071e+05
75,6309-2RS1/C3GJNSKF,11,9.0,18.161602,5.571429,3.259775,5.0,6.0,False,75052.900132,ÚLTIMO_SNAPSHOT_EMPRESA,8.255819e+05,1.513467,7.268081,4,0,6.0,0.506494,MANTENER,"Cobertura pactada 7.27 meses, dentro del rango...",11,8.255819e+05
82,6312-2RS1/C3GJNSKF,4,3.0,6.053867,4.000000,1.513467,4.0,4.0,True,193466.219373,ÚLTIMO_SNAPSHOT_EMPRESA,7.738649e+05,0.504489,7.928816,2,0,4.0,1.000000,MANTENER,"Cobertura pactada 7.93 meses, dentro del rango...",4,7.738649e+05
83,6312-2Z/C3GJNSKF,4,8.0,16.143646,3.714286,4.346366,1.0,5.0,False,169452.741710,ÚLTIMO_SNAPSHOT_EMPRESA,6.778110e+05,1.345304,2.973306,4,0,6.0,0.928571,MANTENER,"Cobertura pactada 2.97 meses, dentro del rango...",4,6.778110e+05
81,6311-2Z/C3GJNSKF,5,10.0,20.179558,3.857143,5.231737,2.0,2.0,True,119411.143397,ÚLTIMO_SNAPSHOT_EMPRESA,5.970557e+05,1.681630,2.973306,6,0,6.0,0.771429,MANTENER,"Cobertura pactada 2.97 meses, dentro del rango...",5,5.970557e+05
88,6314-2Z/C3GJNSKF,2,3.0,6.053867,2.285714,2.648567,4.0,1.0,False,291877.416996,ÚLTIMO_SNAPSHOT_EMPRESA,5.837548e+05,0.504489,3.964408,2,0,4.0,1.142857,MANTENER,"Cobertura pactada 3.96 meses, dentro del rango...",2,5.837548e+05
85,6313-2Z/C3GJNSKF,2,3.0,6.053867,3.714286,1.629887,2.0,4.0,False,235416.602803,ÚLTIMO_SNAPSHOT_EMPRESA,4.708332e+05,0.504489,3.964408,2,0,6.0,1.857143,MANTENER,"Cobertura pactada 3.96 meses, dentro del rango...",2,4.708332e+05
77,6310-2RS1/C3GJNSKF,4,4.0,8.071823,4.428571,1.822670,5.0,6.0,False,117235.067506,ÚLTIMO_SNAPSHOT_EMPRESA,4.689403e+05,0.672652,5.946612,2,0,6.0,1.107143,MANTENER,"Cobertura pactada 5.95 meses, dentro del rango...",4,4.689403e+05
47,6212-2Z/C3GJNSKF,4,3.0,6.053867,6.000000,1.008978,4.0,6.0,False,83849.419557,ÚLTIMO_SNAPSHOT_EMPRESA,3.353977e+05,0.504489,7.928816,2,0,7.0,1.500000,MANTENER,"Cobertura pactada 7.93 meses, dentro del rango...",4,3.353977e+05
76,6309-2Z/C3GJNSKF,5,6.0,12.107735,4.285714,2.825138,6.0,5.0,False,56720.386884,ÚLTIMO_SNAPSHOT_EMPRESA,2.836019e+05,1.008978,4.955510,4,0,6.0,0.857143,MANTENER,"Cobertura pactada 4.96 meses, dentro del rango...",5,2.836019e+05
15,400900SKF,4,4.0,8.071823,3.285714,2.456642,2.0,4.0,False,68956.707540,ÚLTIMO_SNAPSHOT_EMPRESA,2.758268e+05,0.672652,5.946612,2,0,4.0,0.821429,MANTENER,"Cobertura pactada 5.95 meses, dentro del rango...",4,2.758268e+05
40,6209-2Z/C3GJNSKF,6,10.0,20.179558,6.714286,3.005466,10.0,10.0,True,40632.237424,ÚLTIMO_SNAPSHOT_EMPRESA,2.437934e+05,1.681630,3.567967,6,0,10.0,1.119048,MANTENER,"Cobertura pactada 3.57 meses, dentro del rango...",6,2.437934e+05
37,6208-2RS1/C3GJNSKF,6,7.0,14.125691,4.142857,3.409649,1.0,4.0,False,37642.332709,ÚLTIMO_SNAPSHOT_EMPRESA,2.258540e+05,1.177141,5.097096,4,0,6.0,0.690476,MANTENER,"Cobertura pactada 5.10 meses, dentro del rango...",6,2.258540e+05
10,400650SKF,5,5.0,10.089779,3.714286,2.716479,5.0,3.0,False,37079.122211,ÚLTIMO_SNAPSHOT_EMPRESA,1.853956e+05,0.840815,5.946612,4,0,5.0,0.742857,MANTENER,"Cobertura pactada 5.95 meses, dentro del rango...",5,1.853956e+05
38,6208-2Z/C3GJNSKF,5,6.0,12.107735,7.000000,1.729676,9.0,8.0,False,34336.319368,ÚLTIMO_SNAPSHOT_EMPRESA,1.716816e+05,1.008978,4.955510,4,0,9.0,1.400000,MANTENER,"Cobertura pactada 4.96 meses, dentro del rango...",5,1.716816e+05
11,400700SKF,4,3.0,6.053867,4.000000,1.513467,6.0,3.0,False,37844.753942,ÚLTIMO_SNAPSHOT_EMPRESA,1.513790e+05,0.504489,7.928816,2,0,6.0,1.000000,MANTENER,"Cobertura pactada 7.93 meses, dentro del rango...",4,1.513790e+05
3,400300SKF,6,5.0,10.089779,3.000000,3.363260,3.0,3.0,True,21996.498717,ÚLTIMO_SNAPSHOT_EMPRESA,1.319790e+05,0.840815,7.135934,4,0,3.0,0.500000,MANTENER,"Cobertura pactada 7.14 meses, dentro del rango...",6,1.319790e+05
69,6306-2RS1/C3GJNSKF,4,8.0,16.143646,7.571429,2.132180,5.0,7.0,False,30445.999576,ÚLTIMO_SNAPSHOT_EMPRESA,1.217840e+05,1.345304,2.973306,4,0,13.0,1.892857,MANTENER,"Cobertura pactada 2.97 meses, dentro del rango...",4,1.217840e+05
13,400800SKF,3,3.0,6.053867,3.571429,1.695083,5.0,2.0,False,39440.340840,ÚLTIMO_SNAPSHOT_EMPRESA,1.183210e+05,0.504489,5.946612,2,0,5.0,1.190476,MANTENER,"Cobertura pactada 5.95 meses, dentro del rango...",3,1.183210e+05
5,400400SKF,4,5.0,10.089779,7.428571,1.358239,7.0,7.0,True,27332.947672,ÚLTIMO_SNAPSHOT_EMPRESA,1.093318e+05,0.840815,4.757290,4,0,10.0,1.857143,MANTENER,"Cobertura pactada 4.76 meses, dentro del rango...",4,1.093318e+05
34,6206-2Z/C3GJNSKF,5,8.0,16.143646,6.000000,2.690608,5.0,7.0,False,20017.007928,ÚLTIMO_SNAPSHOT_EMPRESA,1.000850e+05,1.345304,3.716632,4,0,8.0,1.200000,MANTENER,"Cobertura pactada 3.72 meses, dentro del rango...",5,1.000850e+05
33,6205-2Z/C3GJNSKF,8,6.0,12.107735,4.000000,3.026934,3.0,2.0,False,11317.949921,ÚLTIMO_SNAPSHOT_EMPRESA,9.054360e+04,1.008978,7.928816,4,0,7.0,0.500000,MANTENER,"Cobertura pactada 7.93 meses, dentro del rango...",8,9.054360e+04
6,400450SKF,4,5.0,10.089779,4.428571,2.278337,7.0,2.0,False,19591.161768,ÚLTIMO_SNAPSHOT_EMPRESA,7.836465e+04,0.840815,4.757290,4,0,7.0,1.107143,MANTENER,"Cobertura pactada 4.76 meses, dentro del rango...",4,7.836465e+04
32,6205-2RSH/C3GJNSKF,5,6.0,12.107735,9.142857,1.324283,6.0,10.0,False,13144.471911,ÚLTIMO_SNAPSHOT_EMPRESA,6.572236e+04,1.008978,4.955510,4,0,13.0,1.828571,MANTENER,"Cobertura pactada 4.96 meses, dentro del rango...",5,6.572236e+04
16,401000SKF,1,2.0,4.035912,4.000000,1.008978,0.0,3.0,False,50985.857745,ÚLTIMO_SNAPSHOT_EMPRESA,5.098586e+04,0.336326,2.973306,1,5,5.0,4.000000,MANTENER,"Cobertura pactada 2.97 meses, dentro del rango...",1,5.098586e+04
29,6203-2Z/C3GJNSKF,6,16.0,32.287293,7.714286,4.185390,11.0,10.0,False,8458.906402,ÚLTIMO_SNAPSHOT_EMPRESA,5.075344e+04,2.690608,2.229979,8,0,11.0,1.285714,MANTENER,"Cobertura pactada 2.23 meses, dentro del rango...",6,5.075344e+04
7,400500SKF,2,2.0,4.035912,6.285714,0.642077,8.0,6.0,False,24446.298858,ÚLTIMO_SNAPSHOT_EMPRESA,4.889260e+04,0.336326,5.946612,1,0,8.0,3.142857,MANTENER,"Cobertura pactada 5.95 meses, dentro del rango...",2,4.889260e+04
28,6203-2RSH/C3GJNSKF,4,5.0,10.089779,7.000000,1.441397,4.0,9.0,False,9847.353939,ÚLTIMO_SNAPSHOT_EMPRESA,3.938942e+04,0.840815,4.757290,4,0,12.0,1.750000,MANTENER,"Cobertura pactada 4.76 meses, dentro del rango...",4,3.938942e+04
23,6200-2Z/C3GJNSKF,4,6.0,12.107735,4.285714,2.825138,7.0,1.0,False,7018.523796,ÚLTIMO_SNAPSHOT_EMPRESA,2.807410e+04,1.008978,3.964408,4,0,7.0,1.071429,MANTENER,"Cobertura pactada 3.96 meses, dentro del rango...",4,2.807410e+04
89,6314-2Z/C3SKF,4,0.0,0.000000,0.000000,NaN,0.0,0.0,True,481576.000000,ÚLTIMA_VENTA,1.926304e+06,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
54,6215-2RS1/C3SKF,5,0.0,0.000000,0.000000,NaN,0.0,0.0,True,223831.914905,ÚLTIMO_SNAPSHOT_EMPRESA,1.119160e+06,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
91,6315-2Z/C3GJNSKF,3,0.0,0.000000,3.000000,0.000000,3.0,3.0,True,369881.959559,ÚLTIMO_SNAPSHOT_EMPRESA,1.109646e+06,0.000000,NaN,0,0,3.0,1.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
95,6319/C3SKF,2,0.0,0.000000,0.000000,NaN,0.0,0.0,True,524357.983629,ÚLTIMO_SNAPSHOT_EMPRESA,1.048716e+06,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
50,6213-2Z/C3GJNSKF,8,0.0,0.000000,4.000000,0.000000,4.0,4.0,True,126997.463231,ÚLTIMO_SNAPSHOT_EMPRESA,1.015980e+06,0.000000,NaN,0,0,4.0,0.500000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
93,6316-2Z/C3SKF,2,0.0,0.000000,0.000000,NaN,0.0,0.0,True,320505.189355,ÚLTIMO_SNAPSHOT_EMPRESA,6.410104e+05,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
52,6214-2RS1/C3SKF,4,0.0,0.000000,0.000000,NaN,0.0,0.0,True,134649.659619,ÚLTIMO_SNAPSHOT_EMPRESA,5.385986e+05,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
96,7312 BECBJSKF,2,0.0,0.000000,0.000000,NaN,0.0,0.0,True,269135.356800,ÚLTIMO_SNAPSHOT_EMPRESA,5.382707e+05,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
57,6217-2Z/C3SKF,2,0.0,0.000000,1.000000,0.000000,1.0,1.0,True,268903.535791,ÚLTIMO_SNAPSHOT_EMPRESA,5.378071e+05,0.000000,NaN,0,0,1.0,0.500000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
53,6214-2Z/C3SKF,3,0.0,0.000000,0.000000,NaN,0.0,0.0,True,176032.240775,ÚLTIMO_SNAPSHOT_EMPRESA,5.280967e+05,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
48,6213-2RS1/C3GJNSKF,4,0.0,0.000000,0.000000,NaN,0.0,0.0,True,131629.311885,ÚLTIMO_SNAPSHOT_EMPRESA,5.265172e+05,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
98,NJ 220 ECJ/C3SKF,1,0.0,0.000000,0.000000,NaN,0.0,0.0,True,516605.822100,ÚLTIMO_SNAPSHOT_EMPRESA,5.166058e+05,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
58,6218-2Z/C3SKF,1,0.0,0.000000,0.000000,NaN,0.0,0.0,True,467499.007682,ÚLTIMO_SNAPSHOT_EMPRESA,4.674990e+05,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
56,6216-2Z/C3SKF,2,0.0,0.000000,0.000000,NaN,0.0,0.0,True,203232.368893,ÚLTIMO_SNAPSHOT_EMPRESA,4.064647e+05,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
78,6310-2RS1/C3SKF,4,0.0,0.000000,0.000000,NaN,0.0,0.0,True,91572.235479,ÚLTIMO_SNAPSHOT_EMPRESA,3.662889e+05,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
55,6215-2Z/C3GJNSKF,2,0.0,0.000000,1.000000,0.000000,1.0,1.0,True,178681.580369,ÚLTIMO_SNAPSHOT_EMPRESA,3.573632e+05,0.000000,NaN,0,0,1.0,0.500000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
45,6211-2Z/C3SKF,4,0.0,0.000000,0.000000,NaN,0.0,0.0,True,66096.557964,ÚLTIMO_SNAPSHOT_EMPRESA,2.643862e+05,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
49,6213-2RS1/C3SKF,2,0.0,0.000000,2.000000,0.000000,2.0,2.0,True,127499.945364,ÚLTIMO_SNAPSHOT_EMPRESA,2.549999e+05,0.000000,NaN,0,0,2.0,1.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
2,400250SKF,9,0.0,0.000000,2.000000,0.000000,2.0,2.0,True,23346.217663,ÚLTIMO_SNAPSHOT_EMPRESA,2.101160e+05,0.000000,NaN,0,0,2.0,0.222222,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
86,6313-2Z/C3SKF,1,0.0,0.000000,0.000000,NaN,0.0,0.0,True,201144.689789,ÚLTIMO_SNAPSHOT_EMPRESA,2.011447e+05,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
21,6007-2RS1/C3GJNSKF,9,0.0,0.000000,8.000000,0.000000,8.0,8.0,True,21686.466194,ÚLTIMO_SNAPSHOT_EMPRESA,1.951782e+05,0.000000,NaN,0,0,8.0,0.888889,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
12,400750SKF,5,0.0,0.000000,2.000000,0.000000,2.0,2.0,True,36680.171194,ÚLTIMO_SNAPSHOT_EMPRESA,1.834009e+05,0.000000,NaN,0,0,2.0,0.400000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
51,6213-2Z/C3SKF,1,0.0,0.000000,0.000000,NaN,0.0,0.0,True,177091.103000,ÚLTIMA_VENTA,1.770911e+05,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
72,6307-2Z/C3GJNSKF,4,0.0,0.000000,3.000000,0.000000,3.0,3.0,True,42910.245652,ÚLTIMO_SNAPSHOT_EMPRESA,1.716410e+05,0.000000,NaN,0,0,3.0,0.750000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
39,6209-2RS1/C3GJNSKF,3,0.0,0.000000,8.000000,0.000000,8.0,8.0,True,45003.865938,ÚLTIMO_SNAPSHOT_EMPRESA,1.350116e+05,0.000000,NaN,0,0,8.0,2.666667,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
19,6005-2Z/C3GJNSKF,10,0.0,0.000000,10.000000,0.000000,10.0,10.0,True,11909.986291,ÚLTIMO_SNAPSHOT_EMPRESA,1.190999e+05,0.000000,NaN,0,0,10.0,1.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
17,6004-2Z/C3GJNSKF,10,0.0,0.000000,1.000000,0.000000,1.0,1.0,True,10249.900614,ÚLTIMO_SNAPSHOT_EMPRESA,1.024990e+05,0.000000,NaN,0,0,1.0,0.100000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
97,99235SKF,2,0.0,0.000000,0.000000,NaN,0.0,0.0,True,47180.286283,ÚLTIMO_SNAPSHOT_EMPRESA,9.436057e+04,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
44,6211-2RS1/C3SKF,1,0.0,0.000000,0.000000,NaN,0.0,0.0,True,78150.389275,ÚLTIMO_SNAPSHOT_EMPRESA,7.815039e+04,0.000000,NaN,0,7,0.0,0.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
1,400200SKF,10,0.0,0.000000,4.000000,0.000000,4.0,4.0,True,6912.320684,ÚLTIMO_SNAPSHOT_EMPRESA,6.912321e+04,0.000000,NaN,0,0,4.0,0.400000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
67,6305-2RS1/C3GJNSKF,3,0.0,0.000000,7.000000,0.000000,7.0,7.0,True,22858.383981,ÚLTIMO_SNAPSHOT_EMPRESA,6.857515e+04,0.000000,NaN,0,0,7.0,2.333333,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
62,6302-2Z/C3GJNSKF,6,0.0,0.000000,6.000000,0.000000,6.0,6.0,True,10964.857394,ÚLTIMO_SNAPSHOT_EMPRESA,6.578914e+04,0.000000,NaN,0,0,6.0,1.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
65,6304-2RSH/C3GJNSKF,4,0.0,0.000000,4.000000,0.000000,4.0,4.0,True,15716.470023,ÚLTIMO_SNAPSHOT_EMPRESA,6.286588e+04,0.000000,NaN,0,0,4.0,1.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00
22,6008-2Z/C3GJNSKF,2,0.0,0.000000,2.000000,0.000000,2.0,2.0,True,30864.678650,ÚLTIMO_SNAPSHOT_EMPRESA,6.172936e+04,0.000000,NaN,0,0,2.0,1.000000,RETIRAR,Sin consumo entre 2026-01-01 y 2026-07-01; ret...,0,0.000000e+00

## Bloque D — ¿Qué sobra y qué falta?

Se separan cuatro conversaciones: retiros, compras del cliente desde otras bodegas,
equivalentes de otra marca y referencias consumidas en la bodega 59 fuera del acuerdo.

In [6]:
print("Candidatas a retirar")
display(metricas[metricas["veredicto"].eq("RETIRAR")][
    ["codigo", "unidades_pactadas", "inventario_promedio",
     "capital_comprometido_ref", "motivo"]
])

dominant_nit = str(identidad.groupby("nit")["lineas"].sum().idxmax())
with sqlite3.connect(uri, uri=True) as con:
    ventas_cliente = pd.read_sql_query(
        "SELECT * FROM raw_sales WHERE CAST(nit AS TEXT)=?", con,
        params=(dominant_nit,),
    )
ventas_cliente["fecha"] = pd.to_datetime(ventas_cliente["fecha"], errors="raise")
cliente_periodo = ventas_cliente[
    ventas_cliente["fecha"].ge(start) & ventas_cliente["fecha"].lt(end)
].copy()
otras_bodegas = cliente_periodo[
    cliente_periodo["idbodega"].astype(str).ne(str(IDBODEGA))
]
compras_fuera = (
    otras_bodegas.groupby(["idproducto", "nombreproducto"])
    .agg(unidades=("cantidad", "sum"), documentos=("numero", "nunique"),
         bodegas=("idbodega", lambda x: ",".join(sorted(set(map(str, x))))))
    .reset_index().sort_values("unidades", ascending=False)
)
display(compras_fuera[compras_fuera["unidades"] > 0].head(100))

agreement_parsed = pd.DataFrame(
    acuerdo["codigo"].map(normalize_designation).tolist(), index=acuerdo.index
)
agreement_keys = set(agreement_parsed.loc[
    agreement_parsed["ok"].fillna(False), "llave_canonica"
])
sales_parsed = pd.DataFrame(
    cliente_periodo["prefijo_1"].map(normalize_designation).tolist(),
    index=cliente_periodo.index,
).add_prefix("parser_")
cliente_norm = pd.concat([cliente_periodo, sales_parsed], axis=1)
otras_marcas = cliente_norm[
    cliente_norm["parser_llave_canonica"].isin(agreement_keys)
    & cliente_norm["sufijo"].fillna("").ne("SKF")
]
substituciones = (
    otras_marcas.groupby(
        ["parser_llave_canonica", "sufijo", "idproducto"], dropna=False
    )["cantidad"].sum().reset_index(name="unidades")
    .sort_values("unidades", ascending=False)
)
display(substituciones[substituciones["unidades"] > 0])

consumo_59 = (
    ventas_periodo.groupby(["idproducto", "nombreproducto"])["cantidad"]
    .sum().reset_index(name="unidades")
)
fuera_acuerdo = consumo_59[
    ~consumo_59["idproducto"].isin(set(acuerdo["codigo"]))
    & consumo_59["unidades"].gt(0)
].sort_values("unidades", ascending=False)
display(fuera_acuerdo.head(100))

Candidatas a retirar

,codigo,unidades_pactadas,inventario_promedio,capital_comprometido_ref,motivo
1,400200SKF,10,4.000000,6.912321e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
2,400250SKF,9,2.000000,2.101160e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
12,400750SKF,5,2.000000,1.834009e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
17,6004-2Z/C3GJNSKF,10,1.000000,1.024990e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
19,6005-2Z/C3GJNSKF,10,10.000000,1.190999e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
20,6006-2Z/C3GJNSKF,1,0.000000,1.811179e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
21,6007-2RS1/C3GJNSKF,9,8.000000,1.951782e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
22,6008-2Z/C3GJNSKF,2,2.000000,6.172936e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
24,6201-2RSH/C3GJNSKF,5,3.000000,4.021134e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
27,6202-2Z/C3GJNSKF,7,11.000000,5.178006e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
39,6209-2RS1/C3GJNSKF,3,8.000000,1.350116e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
44,6211-2RS1/C3SKF,1,0.000000,7.815039e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
45,6211-2Z/C3SKF,4,0.000000,2.643862e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
48,6213-2RS1/C3GJNSKF,4,0.000000,5.265172e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
49,6213-2RS1/C3SKF,2,2.000000,2.549999e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
50,6213-2Z/C3GJNSKF,8,4.000000,1.015980e+06,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
51,6213-2Z/C3SKF,1,0.000000,1.770911e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
52,6214-2RS1/C3SKF,4,0.000000,5.385986e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
53,6214-2Z/C3SKF,3,0.000000,5.280967e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
54,6215-2RS1/C3SKF,5,0.000000,1.119160e+06,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
55,6215-2Z/C3GJNSKF,2,1.000000,3.573632e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
56,6216-2Z/C3SKF,2,0.000000,4.064647e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
57,6217-2Z/C3SKF,2,1.000000,5.378071e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
58,6218-2Z/C3SKF,1,0.000000,4.674990e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
60,6300-2Z/C3SKF,4,0.000000,6.039566e+03,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
61,6302-2RSH/C3GJNSKF,4,1.000000,5.703543e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
62,6302-2Z/C3GJNSKF,6,6.000000,6.578914e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
63,6303-2RSH/C3GJNSKF,2,0.000000,2.390138e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
64,6303-2Z/C3GJNSKF,2,0.000000,2.360907e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
65,6304-2RSH/C3GJNSKF,4,4.000000,6.286588e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
66,6304-2Z/C3GJNSKF,4,3.428571,5.817807e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
67,6305-2RS1/C3GJNSKF,3,7.000000,6.857515e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
72,6307-2Z/C3GJNSKF,4,3.000000,1.716410e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
78,6310-2RS1/C3SKF,4,0.000000,3.662889e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
86,6313-2Z/C3SKF,1,0.000000,2.011447e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
89,6314-2Z/C3SKF,4,0.000000,1.926304e+06,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
91,6315-2Z/C3GJNSKF,3,3.000000,1.109646e+06,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
93,6316-2Z/C3SKF,2,0.000000,6.410104e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
95,6319/C3SKF,2,0.000000,1.048716e+06,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
96,7312 BECBJSKF,2,0.000000,5.382707e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
97,99235SKF,2,0.000000,9.436057e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
98,NJ 220 ECJ/C3SKF,1,0.000000,5.166058e+05,Sin consumo entre 2026-01-01 y 2026-07-01; ret...
99,NU 2211 ECP/C3SKF,1,0.000000,3.364746e+04,Sin consumo entre 2026-01-01 y 2026-07-01; ret...

,idproducto,nombreproducto,unidades,documentos,bodegas
40,MB 22FAG,ARANDELA DE FIJACION,4.0,2,50
37,E-5 ELEMENTREX,7300020-ELASTOMERO,4.0,2,50
34,BWW 120SEE,ARANDELA DE AJUSTE,3.0,2,50
12,55X70X8 VITONSOG,RETENEDOR DE ACEITE EN VITON,3.0,1,72
27,6322 M/C3VL0241SKF,RODAMIENTO RIGIDO DE BOLAS,2.0,1,50
47,RLS 11KOY,RODAMIENTO RIGIDO DE BOLAS,2.0,1,72
23,6319/C3SKF,RODAMIENTO RIGIDO DE BOLAS,2.0,1,50
46,QD-HINT,BUJE QD,2.0,1,72
48,RLS 12-2ZKOY,RODAMIENTO RIGIDO DE BOLAS,2.0,1,72
4,3213 A/C3SKF,RODAMIENTO DE CONTACTO ANGULAR,2.0,2,50
50,SYJ 25 TFSKF,CHUMACERA DE PEDESTAL,2.0,1,50
32,99196SKF,SPEEDI SLEEVE 50 mm - 1.31/32,1.0,1,72
31,99114SKF,SPEEDI SLEEVE 30mm,1.0,1,50
33,AN 19SKF,TUERCA DE FIJACION,1.0,1,50
35,BWW 130SEE,ARANDELA DE AJUSTE,1.0,1,50
30,7309 BECBMSKF,RODAMIENTO DE CONTACTO ANGULAR,1.0,1,50
36,BWW 90SEE,ARANDELA DE AJUSTE,1.0,1,50
0,220X250X15NQK,RETENEDOR DE ACEITE,1.0,1,50
38,KM 19SKF,TUERCA DE FIJACION,1.0,1,50
39,MB 19SKF,ARANDELA DE RETENC.,1.0,1,50
29,6326-M-C3FAG,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
42,NU 313 ECJ/C3SKF,RODAMIENTO DE RODILLOS CILINDRICOS,1.0,1,50
43,P 2A100HINT,POLEA EN V,1.0,1,72
44,P 2A125HINT,POLEA EN V,1.0,1,72
45,P 2B165SDSINT,POLEAS,1.0,1,72
49,SDSINT,BUFFIN SERIE QD,1.0,1,72
51,W 19SKF,ARANDELA DE RETENCION,1.0,1,50
41,NU 222-E-XL-M1-C3FAG,RODAMIENTO DE RODILLOS CILINDRICOS,1.0,1,50
26,6320/C3SKF,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
28,6324/C3SKF,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
1,25X37X7 VITONSOG,RETENEDOR DE ACEITE EN VITON,1.0,1,72
2,260X290X16NQK,RETENEDOR DE ACEITE,1.0,1,50
3,3210-BD-XL-2Z-TVH-C3FAG,RODAMIENTO DE DOBLE HILERA DE BOLAS,1.0,1,50
5,38X62X7NQK,RETENEDOR DE ACEITE,1.0,1,72
6,40X52X7 HMSA10 VSKF,RETENEDOR DE ACEITE,1.0,1,50
7,50X65X8 HMSA10 VSKF,RETENEDOR DE ACEITE,1.0,1,50
8,50X68X8 VITONSOG,RETENEDOR DE ACEITE EN VITON,1.0,1,72
9,50X75X10 VITONSOG,RETENEDOR DE ACEITE EN VITON,1.0,1,72
10,51305SKF,RODAMIENTO AXIAL DE BOLAS,1.0,1,50
11,55X65X8NQK,RETENEDOR DE ACEITE,1.0,1,50
13,6216/C3SKF,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
14,6216SKF,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
15,6220-2RSR-C3FAG,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
16,6220-2Z/C3SKF,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
17,6220-C3FAG,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
18,6222-2Z/C3SKF,RODAMIENTO RIGIDO DE BOLAS,1.0,1,72
19,6316-2Z/C3SKF,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
20,6316-2ZSKF,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
21,6318-2Z-C3FAG,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
22,6318-2Z/C3GJNSKF,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
24,6320 M/C3VL0241SKF,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
25,6320-C3FAG,RODAMIENTO RIGIDO DE BOLAS,1.0,1,50
52,YAR 203-010-2FSKF,RODAMIENTO TIPO Y,1.0,1,72

Empty DataFrame
Columns: [parser_llave_canonica, sufijo, idproducto, unidades]
Index: []

            idproducto              nombreproducto  unidades
27  6206-2RS1/C3GJNSKF  RODAMIENTO RIGIDO DE BOLAS      15.0
23     6204-2RSH/C3SKF  RODAMIENTO RIGIDO DE BOLAS       4.0
37    6211-2Z/C3GJNSKF  RODAMIENTO RIGIDO DE BOLAS       4.0
65          6318/C3SKF  RODAMIENTO RIGIDO DE BOLAS       3.0
66       6319-2Z/C3SKF  RODAMIENTO RIGIDO DE BOLAS       3.0
13           400950SKF         V-RING 95mm - 3.3/4       2.0
15           401100SKF        V-RING 110mm - 4.1/2       2.0
63     6317-2RS1/C3SKF  RODAMIENTO RIGIDO DE BOLAS       2.0
64    6318-2Z/C3GJNSKF  RODAMIENTO RIGIDO DE BOLAS       2.0
59          6314/C3SKF  RODAMIENTO RIGIDO DE BOLAS       1.0
67           BWW 47SEE          ARANDELA DE AJUSTE       1.0

## Bloque E — Facturación, capital comprometido y escenario antes/después

La referencia financiera única del convenio es el **capital comprometido**:
`unidades pactadas × costo actual`. El costo actual se toma del snapshot más reciente
disponible en la empresa y, si la referencia no aparece en inventario, de su venta más
reciente.

El inventario físico promedio observado se informa aparte como métrica operativa; no se
usa como denominador de rotación o retorno. Julio contiene información hasta la última
fecha disponible en ventas y por ello puede ser un mes parcial.

In [7]:
ventas_fin = ventas[
    ventas["fecha"].ge(pd.Timestamp("2026-01-01"))
    & ventas["fecha"].lt(pd.Timestamp("2026-08-01"))
].copy()
ventas_fin["mes"] = ventas_fin["fecha"].dt.to_period("M")
ventas_fin["costo_vendido"] = ventas_fin["cantidad"] * ventas_fin["costo"]
mensual = (
    ventas_fin.groupby("mes")
    .agg(
        facturacion_bruta=("neto", "sum"),
        costo_vendido=("costo_vendido", "sum"),
    )
    .reindex(pd.period_range("2026-01", "2026-07", freq="M"), fill_value=0)
)
mensual["margen"] = mensual["facturacion_bruta"] - mensual["costo_vendido"]
mensual.index = mensual.index.astype(str)
mensual.index.name = "mes"
promedio = mensual.mean().to_frame().T
promedio.index = ["PROMEDIO_MENSUAL"]
mensual_con_promedio = pd.concat([mensual, promedio])
display(mensual_con_promedio.style.format({
    "facturacion_bruta": PESO, "costo_vendido": PESO, "margen": PESO,
}))
ultima_fecha_ventas = ventas_fin["fecha"].max()
print(f"Última fecha incluida en julio: {ultima_fecha_ventas:%Y-%m-%d}")

capital_comprometido = metricas["capital_comprometido_ref"].sum()
capital_propuesto = metricas["capital_propuesto_ref"].sum()
capital_liberado = capital_comprometido - capital_propuesto
reduccion_capital = (
    capital_liberado / capital_comprometido if capital_comprometido else np.nan
)
costo_anualizado = mensual["costo_vendido"].mean() * 12
margen_anualizado = mensual["margen"].mean() * 12

inventario["valor_fisico"] = inventario["unidades"] * inventario["costo_unitario"]
valor_fisico_por_snapshot = (
    inventario.groupby("fecha_snapshot")["valor_fisico"].sum().reset_index()
)
inventario_fisico_promedio = valor_fisico_por_snapshot["valor_fisico"].mean()

escenario = pd.DataFrame({
    "Escenario": ["ANTES — pacto vigente", "DESPUÉS — niveles propuestos"],
    "Capital comprometido": [capital_comprometido, capital_propuesto],
    "Rotación anualizada": [
        costo_anualizado / capital_comprometido,
        costo_anualizado / capital_propuesto,
    ],
    "Retorno anualizado": [
        margen_anualizado / capital_comprometido,
        margen_anualizado / capital_propuesto,
    ],
})
display(escenario.style.format({
    "Capital comprometido": PESO,
    "Rotación anualizada": "{:.2f}x",
    "Retorno anualizado": "{:.1%}",
}))

operacion = pd.DataFrame({
    "Métrica operativa (no capital contractual)": [
        "Inventario físico promedio observado",
        "Snapshots incluidos",
    ],
    "Valor": [PESO(inventario_fisico_promedio), str(len(fechas_snapshot))],
})
display(operacion)
display(valor_fisico_por_snapshot.style.format({"valor_fisico": PESO}))

print(
    f"Aplicar los veredictos libera {PESO(capital_liberado)} "
    f"({reduccion_capital:.1%}) de capital comprometido; con el mismo margen "
    f"mensual observado, el retorno anualizado pasa de "
    f"{margen_anualizado / capital_comprometido:.1%} a "
    f"{margen_anualizado / capital_propuesto:.1%}."
)

ventas["anio"] = ventas["fecha"].dt.year
crecimiento = (
    ventas.groupby("anio")
    .agg(unidades=("cantidad", "sum"), ventas_netas=("neto", "sum"),
         lineas=("idproducto", "size"))
    .reset_index()
)
display(crecimiento.style.format({"unidades": "{:,.0f}", "ventas_netas": PESO}))

Última fecha incluida en julio: 2026-07-14

  Métrica operativa (no capital contractual)        Valor
0       Inventario físico promedio observado  $20,258,283
1                        Snapshots incluidos            7

Aplicar los veredictos libera $19,623,376 (58.1%) de capital comprometido; con el mismo margen mensual observado, el retorno anualizado pasa de 89.1% a 212.5%.

## Tabla consolidada final

Cada fila corresponde a una referencia exacta del acuerdo. El capital comprometido usa
las unidades pactadas; el capital propuesto aplica el veredicto y el nivel simple. La
rotación por referencia y cobertura usan el periodo comparable entre snapshots.

In [8]:
final = metricas[[
    "codigo", "unidades_pactadas", "consumo_periodo", "consumo_mensual",
    "meses_cobertura", "veces_en_cero", "inventario_medio_vs_pactado",
    "rotaciones_anualizadas",
    "inventario_promedio", "inventario_final", "costo_actual",
    "capital_comprometido_ref", "unidades_propuestas",
    "capital_propuesto_ref", "veredicto", "motivo",
]].rename(columns={
    "codigo": "Referencia",
    "unidades_pactadas": "Pactado",
    "consumo_periodo": "Consumo 2026 comparable",
    "consumo_mensual": "Consumo mensual",
    "meses_cobertura": "Meses cobertura",
    "veces_en_cero": "Veces en cero",
    "inventario_medio_vs_pactado": "Inventario medio / pactado",
    "rotaciones_anualizadas": "Rotación anualizada",
    "inventario_promedio": "Inventario promedio",
    "inventario_final": "Inventario último snapshot",
    "costo_actual": "Costo actual",
    "capital_comprometido_ref": "Capital comprometido",
    "unidades_propuestas": "Unidades propuestas",
    "capital_propuesto_ref": "Capital propuesto",
    "veredicto": "Veredicto",
    "motivo": "Motivo",
})
orden = {"SUBIR": 0, "RETIRAR": 1, "BAJAR": 2, "MANTENER": 3}
final["_orden"] = final["Veredicto"].map(orden)
final = final.sort_values(
    ["_orden", "Capital comprometido"], ascending=[True, False]
).drop(columns="_orden")
display(final.style.format({
    "Pactado": "{:,.0f}",
    "Consumo 2026 comparable": "{:,.1f}",
    "Consumo mensual": "{:,.1f}",
    "Meses cobertura": "{:,.2f}",
    "Veces en cero": "{:,.0f}",
    "Inventario medio / pactado": "{:.0%}",
    "Rotación anualizada": "{:,.1f}",
    "Inventario promedio": "{:,.1f}",
    "Inventario último snapshot": "{:,.0f}",
    "Costo actual": PESO,
    "Capital comprometido": PESO,
    "Unidades propuestas": "{:,.0f}",
    "Capital propuesto": PESO,
}, na_rep="—"))

resumen_final = (
    final.groupby("Veredicto")
    .agg(referencias=("Referencia", "size"), pactado=("Pactado", "sum"),
         propuesto=("Unidades propuestas", "sum"),
         capital_antes=("Capital comprometido", "sum"),
         capital_despues=("Capital propuesto", "sum"))
    .reindex(["SUBIR", "MANTENER", "BAJAR", "RETIRAR"])
    .dropna(how="all").reset_index()
)
display(resumen_final.style.format({
    "referencias": "{:,.0f}", "pactado": "{:,.0f}", "propuesto": "{:,.0f}",
    "capital_antes": PESO, "capital_despues": PESO,
}))

## Exportación opcional

El notebook es el entregable. Active la bandera solo si necesita extraer las tablas.

In [9]:
EXPORTAR = False
if EXPORTAR:
    output = Path("outputs/mym_bodega59")
    output.mkdir(parents=True, exist_ok=True)
    final.to_csv(output / "tabla_consolidada.csv", index=False)
    resumen_intervalos.to_csv(output / "reconciliacion_intervalos.csv", index=False)
    fuera_acuerdo.to_csv(output / "fuera_acuerdo.csv", index=False)
    print(f"Exportado en {output.resolve()}")
else:
    print("Exportación desactivada.")

Exportación desactivada.